#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)


f = Filter()
f.add(from_string = 'Final results from EXACORR',
      num_lines   = 8,
      abs_tolerance   = 1.0e-5)

test.run(['exat_ccsd_h2O.inp'], ['H2O_nosym.mol'], f)
test.run(['exat_cholesky_li2.inp'], ['Li2_nosym.mol'], f)
test.run(['exat_cholesky_lio.inp'], ['LiO_nosym.mol'], f)

sys.exit(test.return_code)
