#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

my_scratchdir = os.path.join(os.getcwd(), 'cc_scratchdir')
if os.path.lexists(my_scratchdir):
   files_to_delete = os.listdir(my_scratchdir)
   for f in files_to_delete:
      os.unlink(os.path.join(my_scratchdir,f))
   os.rmdir(my_scratchdir)

f = Filter()

f.add(from_string = ' Overview of calculated energies',
      to_string   = '@ MP2 correlation energy',
      rel_tolerance   = 1.0e-6)

inputs = ['ccsd_integrals.inp', 'ccsd_restart.inp']
test.run(inputs, ['H2O.mol'], f, args='--mw=64 --aw=130 --keep_scratch --scratchful='+my_scratchdir)

f = Filter()

f.add(from_string = ' Overview of calculated energies',
      to_string   = '@ Total CCSD-T  energy',
      rel_tolerance   = 1.0e-7)

test.run(['ccsd_restart_othergeo.inp'], ['H2O_2.mol'], f, args='--mw=64 --aw=130 --keep_scratch --scratchful='+my_scratchdir)

files_to_delete = os.listdir(my_scratchdir)
for f in files_to_delete:
   os.unlink(os.path.join(my_scratchdir,f))
os.rmdir(my_scratchdir)

sys.exit(test.return_code)
