#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Total energy',
      rel_tolerance = 1.0e-7)

test.run(['export.inp'], ['hehe.mol'],    args='--get numerical_grid')
test.run(['import.inp'], ['hegh.mol'], f, args='--put numerical_grid')

os.unlink('numerical_grid')

sys.exit(test.return_code)
