#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '                London Cotton-mouton constant',
      num_lines   = 12,
      rel_tolerance   = 1.0e-7)

test.run(['nr.inp', 'dc_skipep_cval=800.inp', 'dc_shifted.inp'], ['hf.mol'], f)

sys.exit(test.return_code)
