#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '   * dipole moment for electronic state:   1 (   a)',
      num_lines   = 83,
      ignore_sign = True,
      rel_tolerance   = 1.0e-4)

test.run(['h3.inp'], ['H3.mol'], f)

sys.exit(test.return_code)
