#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

options = cli()

ierr = 0
ierr += run(options,
            configure,
            input_files=['response_1z_bz.inp', 'co.mol'],
            extra_args='--get="DFCOEF PAMXVC"')

f = [
    get_filter(from_string='r_x           r_y           r_z            scalar',
               num_lines=7,
               rel_tolerance=1.0e-4),
]

for inp in ['visual_1z_bz.inp',
            'visual_1z_bz_only_para.inp',
            'visual_divj.inp',
            'visual_divs.inp',
            'visual_j.inp',
            'visual_jdia.inp',
            'visual_rotj.inp']:
    ierr += run(options,
                configure,
                input_files=[inp, 'co.mol'],
                extra_args='--copy="DFCOEF PAMXVC"',
                filters={'out': f})

f = [
    get_filter(from_string='r_x           r_y           r_z            scalar',
               num_lines=7,
               rel_tolerance=1.0e-4,
               skip_below=1.0e-8),
]

for inp in ['visual_jpara.inp',
            'visual_s.inp',
            'visual_rots.inp']:
    ierr += run(options,
                configure,
                input_files=[inp, 'co.mol'],
                extra_args='--copy="DFCOEF PAMXVC"',
                filters={'out': f})

sys.exit(ierr)
