#!/usr/bin/env python

import os
import sys
import shutil

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string  = '   Electronic energy',
      num_lines    = 1,
      rel_tolerance    = 1.0e-10)
f.add(from_string  = '   Solvation energy',
      num_lines    = 1,
      rel_tolerance    = 1.0e-7)
f.add(from_string  = '   Total energy',
      num_lines    = 1,
      rel_tolerance    = 1.0e-10)

test.run(['nonrel.inp'], ['CH4.mol'], f)
test.run(['levy.inp', 'dc.inp', 'dc-skipss.inp', 'dc-lda.inp', 'levy-lda.inp', 'spinfree.inp'], ['CH4.mol'], f, args='--put @pcmsolver.inp')

sys.exit(test.return_code)
