# set cdash buildname
set(BUILDNAME
    "${CMAKE_SYSTEM_NAME}-${CMAKE_HOST_SYSTEM_PROCESSOR}-${CMAKE_Fortran_COMPILER_ID}-${BLAS_TYPE}-${cmake_build_type_tolower}"
    CACHE STRING
    "Name of build on the dashboard"
    )

# set ctest own timeout
set(DART_TESTING_TIMEOUT
    "1500"
    CACHE STRING
    "Set timeout in seconds for every single test"
    )
message(STATUS "Set CDash default timeout for single test set to ${DART_TESTING_TIMEOUT} seconds. Overwritten by test's TIMEOUT property label and, ultimatively, by pam timeout setting.")

macro(dirac_test _name _label _timeout)
    add_test(${_name} ${PYTHON_EXECUTABLE} ${PROJECT_SOURCE_DIR}/test/${_name}/test --binary-dir=${PROJECT_BINARY_DIR} --work-dir=${PROJECT_BINARY_DIR}/test/${_name} --verbose)
    if(NOT "${_label}" STREQUAL "")
        #miro: test's TIMEOUT marker goes after the LABEL marker
        if(NOT "${_timeout}" STREQUAL "")
            set_tests_properties(${_name} PROPERTIES LABELS "${_label}" TIMEOUT "${_timeout}")
            message(STATUS "Test's '${_name}' timeout set to ${_timeout} seconds. Can be overwritten by pam's timeout setting.")
        else()
            set_tests_properties(${_name} PROPERTIES LABELS "${_label}")
        endif()
    endif()
endmacro()

# activate ctest
include(CTest)
enable_testing()
# these tests appear also in release-xx versions
dirac_test(mobasis_hartreefock "short" "")
dirac_test(dft_alda_xcfun "long;dft" "")
dirac_test(dft_alda "long;dft" "")
dirac_test(stex "short;stex" "")
dirac_test(geo_opt "long;geoopt" "")
dirac_test(geo_opt_xyz "long;geoopt" "")
dirac_test(geo_opt_symm_xyz "long;geoopt" "")
dirac_test(london_properties_symmetry "short;lao" "")
dirac_test(response_pv_nmr "long;response" "")
dirac_test(krci_energy "long;krci" "")
dirac_test(molecular_mean_field_hamiltonian_schemes "long;meanfield" "")
dirac_test(electrostatic_potential "long;elp" "")
dirac_test(mp2_properties "long;mp2;property" "")
if(ENABLE_LAPLACE)
   dirac_test(laplace "mp2;laplace" "")
endif()
dirac_test(ffpt_dipmom_polariz_relcc "cc" "")
dirac_test(reladc_sip "reladc" "")
dirac_test(reladc_sipeigv "reladc" "")
dirac_test(reladc_dip "reladc" "")
dirac_test(reladc_fano "reladc" "")
dirac_test(polprp_ph "polprp" "")
dirac_test(cc_energy_and_mp2_dipole "cc" "")
dirac_test(eomcc "short;cc;eomcc" "")
dirac_test(eomcc_long "short;cc;eomcc" "")
dirac_test(eomip_energy_symmetry "cc;eomcc" "")
dirac_test(eomip_energy_symmetry_eigenvalue_shift "cc;eomcc" "")
dirac_test(eomee_energy_symmetry_eigenvalue_shift "cc;eomcc" "")
dirac_test(eomip_energy_symmetry_cvs "cc;eomcc" "")
dirac_test(eomee_energy_symmetry_cvs "cc;eomcc" "")
dirac_test(eomea_energy_symmetry "cc;eomcc" "")
dirac_test(eomee_energy_symmetry "cc;eomcc" "")
dirac_test(count_cc_memory "cc" "")
dirac_test(eomee_fc_cvs "cc;eomcc" "")
dirac_test(eomip_fc_cvs "cc;eomcc" "")
dirac_test(cisd_energy "ci" "")
dirac_test(cosci_average "ci;cosci" "")
dirac_test(dft_ao_eval "dft" "")
dirac_test(dft_geo_opt "dft;geoopt" "")
dirac_test(dft_response "response;dft" "")
dirac_test(dft_response_symmetry "response;dft" "")
dirac_test(dft_response_xcfun "response;dft" "")
dirac_test(efg "efg" "")
dirac_test(fde_static-vemb_dipole "fde" "")
dirac_test(fde_open-shell "fde" "")
dirac_test(fde_response_autodiff "short;fde" "")
dirac_test(fde_export_density "short;fde" "")
dirac_test(fde_interaction_energy "fde" "")
dirac_test(fde_response_mag "fde;magnetizabilities;lao" "")
dirac_test(fde_response_shield "fde;shielding;lao" "")
dirac_test(frozen_orbitals "frozen" "")
dirac_test(fscc_restart "fscc;restart" "")
dirac_test(cc_restart "cc;restart" "")
dirac_test(fscc "fscc" "")
dirac_test(fscc_highspin "fscc" "")
dirac_test(ihfscc_newshift "fscc" "")
dirac_test(geo_opt_saddle "geoopt" "")
dirac_test(huckel_start "huckel" "")
dirac_test(lucita_large "krci" "")
dirac_test(mcscf_energy "mcscf" "")
dirac_test(response_excitation_energies "response" "")
dirac_test(response_nmr_spin-spin "response;nmr" "")
dirac_test(response_qr "response;qr" "")
dirac_test(visual_lao_current "visual;lao" "")
dirac_test(visual_lao_symmetry "visual;lao" "")
dirac_test(xyz_input "input;xyz" "")
dirac_test(krci_energy_q_corrections "medium;krci;qcorr;ci" "")
dirac_test(dirrci_property "ci;dirrci;property" "")
dirac_test(general_property_krci "krci;property" "")
dirac_test(nmqm_property_krci "krci;property" "")
dirac_test(eedm_mhyp_ensps_krci "krci;property" "")
dirac_test(acmoin "short" "")
dirac_test(atomic_start "short" "")
dirac_test(basis_automatic_augmentation "basis;short" "")
dirac_test(basis_contraction "basis;short" "")
dirac_test(basis_input "basis;short" "")
dirac_test(basis_input_scripted "basis;short" "3600")
dirac_test(bsse "basis;short" "")
dirac_test(bss_energy "short" "")
dirac_test(pam_test "short;pam" "")
dirac_test(cc_essential "medium;cc" "")
dirac_test(cc_linear "short;cc" "")
dirac_test(cc_gradient "cc;cc_gradient" "")
dirac_test(cc_frozen_open_shell "cc;frozen" "")
dirac_test(cc_mcscf "cc" "")
dirac_test(cosci_energy_spinfree "short;ci" "")
dirac_test(cosci_methods "short;ci" "")
dirac_test(cosci_tmom "short;ci" "")
dirac_test(density_at_nuclei "short" "")
dirac_test(dft_betasigma "short;dft" "")
dirac_test(dft_cam "short;dft" "")
dirac_test(dft_erf_xcfun "short;dft" "")
dirac_test(dft_lao_mag_prop "short;dft;lao;property" "")
dirac_test(dft_pp86 "short;dft" "")
dirac_test(dirac_mointegral_export "short;cc" "")
dirac_test(ecp "short;ecp" "")
dirac_test(ecp_nio6 "short;ecp" "")
dirac_test(free-particle_projection "short;projection" "")
dirac_test(gaunt "short;gaunt" "")
dirac_test(krci_properties_perm_dipmom "short;krci" "")
dirac_test(linear_structures "structures;short" "")
dirac_test(mcscf_properties "short;mcscf" "")
dirac_test(mp2_energy "short;mp2" "")
dirac_test(mp2_srdft_energies "short;mp2;srdft" "")
dirac_test(mp2_natural_orbitals "short;mp2" "")
dirac_test(open-shells "short" "")
dirac_test(projection_analysis "medium;projection" "")
dirac_test(pvc_scf "short;pvc;scf" "")
dirac_test(response_C6 "short;response" "")
dirac_test(response_hf_polarizability "short;response;polarizabilities" "")
dirac_test(response_lao_shield "short;response;shielding;lao" "")
dirac_test(response_lao_magnetiz "short;response;magnetizabilities;lao" "")
dirac_test(response_lao_magnetiz_dft "short;response;magnetizabilities;lao;dft" "")
dirac_test(response_nmr_levy-leblond "short;response;nmr" "")
dirac_test(response_rkbimp_shield "short;response;shield" "")
dirac_test(symmetry_recognition "short" "")
dirac_test(visual_div_rot "short;visual" "")
dirac_test(visual_lao_shielding "medium;visual;lao" "")
dirac_test(visual_frac_occupation "short;visual" "")
dirac_test(lucita_short "short;krci" "")
dirac_test(xyz_symmetry_recognition "short" "")
dirac_test(zora "short;zora" "")
dirac_test(dft_ac "short;dft" "")
dirac_test(dft_grid_export_import "short;dft;grid" "")
dirac_test(localization "short;localization" "")
dirac_test(krci_properties_omega_tdm "short;krci;property" "")
dirac_test(visual_elf "short;visual" "")
dirac_test(visual_gamma5 "short;visual" "")
dirac_test(visual_general "short;visual" "")
dirac_test(symmetry_scf_energy "medium;scf" "")
dirac_test(atomic_supersymmetry "short;scf" "")
dirac_test(scf_levelshift "short;scf;levelshift" "")
dirac_test(response_complex "short;response;complex" "")
dirac_test(response_nonrel "short;response;nonrel" "")
dirac_test(cosci_energy "short;ci;cosci" "")
dirac_test(lucita_q_corrections "short;qcorr;ci" "")
dirac_test(x2c-SCF_to_4c-SCF "short;x2c;4c;scf" "")
dirac_test(import_mos "short;import;scf;mcscf" "")
dirac_test(operators_mo_mtx_elements "short;operators" "")
dirac_test(spinorbit-from-spinfree "short;scf;resolve" "")
dirac_test(spinrot "medium;response" "")
dirac_test(rotg "medium;response" "")
dirac_test(molecular_mean_field_restart "short;x2c;mp2" "")
dirac_test(bed_isotropic "short;response;bed" "")
dirac_test(bed_anisotropic "short;response;bed" "")
# disabled some tests waiting for code verification/efficiency improvement
#dirac_test(eomcc_expval "short;cc" "")
