cmake_dependent_option(ENABLE_UNRELEASED "Enable unreleased functionality" ON
                       "NOT IS_EXPORTED_TARBALL" OFF)

if(ENABLE_UNRELEASED)
    add_definitions(-DMOD_UNRELEASED)
    dirac_test(blockd_twocomp "twocomp" "")
    dirac_test(cosci_energy_blockd "cosci" "")
    dirac_test(fscc_intensities "cc;fscc" "")
    dirac_test(dft_overlap_diagnostic "dft" "")
    dirac_test(dft_minnesota "dft" "")
    dirac_test(dft_cosci "dft;cosci" "")
    dirac_test(projection_analysis_overlaps "short;projection" "")
    dirac_test(e_edm_finite_field "cc" "")
    dirac_test(ne_sps_finite_field "cc" "")
    dirac_test(nucl_anapole_cc_finite_field "cc" "")
    dirac_test(magn_hyperfine_finite_field "cc" "")
    dirac_test(nmqm_operator "cc" "")
else()
    set(CODE_REMOVAL_FLAGS ${CODE_REMOVAL_FLAGS} -UMOD_UNRELEASED)
endif()
