#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '   freq/cm-1  freq/au     mm         m0m1',
      num_lines   = 14,
      rel_tolerance   = 2.0e-4)
f.add(from_string = '   freq/cm-1  freq/au     ma        m0a12',
      num_lines   = 14,
      rel_tolerance   = 2.0e-4)

test.run(['pv_beta_nr.inp', 'pv_gamma_nr.inp', 'pv_gamma_dc.inp'], ['ch4.mol'], f, args='--copy=DALTON.HES')

sys.exit(test.return_code)
