#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Energy eigenvalues in atomic units',
      to_re       = 'Relative real eigenvalues in other units;',
      rel_tolerance = 1.0e-5)

test.run(['eom_ip.inp', 'eom_ip_dc_sym_overlap.inp'], ['h2o.xyz'], f, args='--mw=110')
#LV: ea for water is unreliable, messes up CI so deactivated
#LV: test.run(['eom_ea.inp'], ['h2o.xyz'], f, args='--mw=110')
test.run(['eom_ee_linear_0g.inp'], ['f2.xyz'], f, args='--mw=110')

sys.exit(test.return_code)
