#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)


f = Filter()
f.add(from_string = 'MP2 energy =',
      num_lines   = 1,
      abs_tolerance   = 1.0e-6)
f.add(from_string = 'Final CCSD energy',
      num_lines   = 4,
      abs_tolerance   = 1.0e-6)

test.run(['ccsd_x2c_scheme1.inp'], ['H2O_nosym.mol'], f)
test.run(['ccsd_x2c_scheme2.inp'], ['H2O_nosym.mol'], f)
test.run(['ccsd_x2c_scheme3.inp'], ['H2O_nosym.mol'], f)
test.run(['ccsd_x2c_scheme4.inp'], ['H2O_nosym.mol'], f)

sys.exit(test.return_code)
