#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Energy eigenvalues in atomic units',
      to_re       = 'Relative real eigenvalues in other units;',
      rel_tolerance   = 2.0e-5)

f.add(from_string = 'Isotropic oscillator strengths (generalized velocity gauge) above threshold',
      to_string   = 'Sum of oscillator strengths (general length) :',
      rel_tolerance   = 2.0e-4)

test.run(['PBE.inp'],        ['CO.mol'], f, args='--outcmo')
test.run(['PBE_skipep.inp'], ['CO.mol'], f, args='--incmo')

# cleanup
os.unlink('DFCOEF')

sys.exit(test.return_code)
