      PARAMETER (NFLAG = 80, MAXRTS = 20, MXFELT = 20)
      COMMON /INTINP/ ISPIN,ISTATE,LSYM,NACTEL, MCTYPE,
     *                LSOLMX,NLMSOL,NELMN1,NELMX1,NELMN3,NELMX3,
     *                LROOTS,NROOTS,IROOT(MAXRTS),KAVER,KSYM(4),
     *                NOROT(MXCORB),ITMPMO(2*MXCORB),
     *                IORTO,ICI0,KDEL,ICHECK,NTIT,
     *                MAXMAC,MAXMIC,MAXJT,MAXCIT,MAXUIT,MAXAPM,MAXABS,
     *                MAXFCK, ITRLVL,ITRFIN,JCHSYM,JCHORB,
     *                NROOCI,ISTACI,NFIELD, MXCIMA, ICICNO,IMCCNO,
     *                MXDIIS,MAXEVC
      DIMENSION IMOORD(MXCORB)
      EQUIVALENCE (IMOORD,ITMPMO)
      LOGICAL FLAG,  DORHF, DOMP2, DOCINO,DOCI,  DOMC,  DORSP,H1VORB,
     &        LNOROT,LMOORD,DIRFCK,CORHOL,CORRLX,RESPHP,JOLSEN,ABAIPH,
     &        INERSI,INERSF,SUPSYM,PARSIR
      COMMON /LOGINP/ FLAG(NFLAG), DORHF,DOMP2,DOCINO,DOCI,DOMC,DORSP,
     &                H1VORB,LNOROT,LMOORD,DIRFCK,CORHOL,CORRLX,RESPHP,
     &                JOLSEN,ABAIPH,INERSI,INERSF,PARSIR
      EQUIVALENCE (SUPSYM,FLAG(17))
      COMMON /RELINP/ SPIN,POTNUC, EPSOL,EPSTAT,RSOL(3),
     &                THRGRD, THRPWF, THRRHF, THRCI, THRMC, THRCGR,
     &                EFIELD(MXFELT), TITMOL(12,2), CMAXMO, THROVL,
     &                THRSSY
      CHARACTER*10 LVLCDK(2)
C     LVLCDK() = (SIRCDK, DETCDK)
      CHARACTER*60 TITLE
      CHARACTER*4  CENT,   TYPE,   CTMPMO
      CHARACTER*8  LFIELD
      COMMON /CHRINP/ LVLCDK, TITLE(6), CENT(MXCORB), TYPE(MXCORB),
     &                CTMPMO(MXCORB), LFIELD(MXFELT)
