#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

f = [
    get_filter(from_string='Level  eigenvalue (eV)  Eigenvalue (cm-1)',
               to_string='Analysis of eigenvectors of the effective Hamiltonian',
               rel_tolerance=1.0e-6)
]

options = cli()

ierr = 0
#for inp in ['Cl-.dc_rkb.1fs.scf_fscc10.inp', 'Cl-.dc_rkb.1fs.scf_fscc10_iAx.1e-4.inp']:
for inp in ['Cl-.dc_rkb.1fs.scf_fscc10.inp']:
    for mol in ['Cl.ccpVDZ.C2.mol']:
        ierr += run(options,
                    configure,
                    input_files=[inp, mol],
                    extra_args='--put "DFPCMO.Cl-.C2.ccpVDZ=DFPCMO"',
                    filters={'out': f})

sys.exit(ierr)

