#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Final L1amp',
      num_lines   = 2,
      rel_tolerance   = 1.0e-9)

f.add(from_string = 'Total contribution to principal components',
      to_string   = '1 a.u. =',
      rel_tolerance   = 1.0e-6)

test.run(['cc2_x2c.inp'], ['h2o.xyz'], f)
test.run(['cc2_energy_large_cvalue.inp'], ['h2o.xyz'], f)

sys.exit(test.return_code)
