#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Electronic energy',
      num_lines   = 8,
      rel_tolerance   = 1.0e-9)
f.add(from_string = 'Eigenvalues',
      to_re       = 'HOMO - LUMO',
      rel_tolerance   = 1.0e-5)
f.add(from_string = 'contribution             contribution             contribution',
      num_lines   = 5,
      rel_tolerance   = 1.0e-5)
f.add(from_string = 'Quadratic Response Functions',
      to_string   = '@   average',
      rel_tolerance   = 1.0e-5)
f.add(from_string = '@            isotropic shielding',
      num_lines   = 5,
      rel_tolerance   = 1.0e-5)

test.run(['gaunt.inp'], ['Ne.C2.mol'], f)

sys.exit(test.return_code)
