      REAL*8 CTRAN(MXCORB, 8)
      INTEGER ITRAN(MXCORB, 8), IAOAO(MXCORB), IPTYP(MXCORB),           &
     &        IPCEN(MXCORB), JTRAN(MXCORB)
      COMMON /AOSOTR/ CTRAN, ITRAN, IAOAO, IPTYP, IPCEN, JTRAN
