      LOGICAL BIGVEC, SEGMEN, SEGMSH(MXSHEL), SPHRSH(MXSHEL)
      REAL*8 CENTSH(MXSHEL, 3)
      INTEGER MAXSHL, NLRGBL, NSMLBL, NHKTSH(MXSHEL), KHKTSH(MXSHEL),   &
     &        KCKTSH(MXSHEL), ISTBSH(MXSHEL), NUCOSH(MXSHEL),           &
     &        NORBSH(MXSHEL), NSTRSH(MXSHEL), NCNTSH(MXSHEL),           &
     &        NSETSH(MXSHEL, 2), JSTRSH(MXSHEL, MXAOVC, 2),             &
     &        NPRIMS(MXSHEL, MXAOVC, 2), NCONTS(MXSHEL, MXAOVC, 2),     &
     &        IORBSH(MXSHEL, MXAOVC), IORBSB(0:MXCORB-1), NRCSH(MXSHEL),&
     &        LCLASH(MXSHEL), NLRBL, ISYMBL(MXSHEL, 8), NSYMBL
      COMMON /BLOCKS/ CENTSH, MAXSHL, BIGVEC, SEGMEN, NLRGBL, NSMLBL,   &
     &                NHKTSH, KHKTSH, KCKTSH, ISTBSH, NUCOSH, NORBSH,   &
     &                NSTRSH, NCNTSH, NSETSH, JSTRSH, NPRIMS, NCONTS,   &
     &                IORBSH, IORBSB, NRCSH, SEGMSH, LCLASH, SPHRSH,    &
     &                NLRBL, ISYMBL, NSYMBL
