      LOGICAL RUNTWO, RTNTWO, TKTIME, SOFOCK, USRSCR, NCLHER
      INTEGER IPRTWO, IPRNTA, IPRNTB, IPRNTC, IPRNTD, ICEDIF, IFTHRS
      REAL*8 THRTWO
      COMMON /CBIHR2/ RUNTWO, IPRTWO, IPRNTA, IPRNTB, IPRNTC, IPRNTD,   &
     &                THRTWO, RTNTWO, TKTIME, ICEDIF, SOFOCK, USRSCR,   &
     &                NCLHER, IFTHRS

      REAL*8 THRFAC(2), SCRFCK
      COMMON /CBRHR2/ THRFAC, SCRFCK
