      LOGICAL COMPAR, SKIP, NOROT1, HESTRO, GDTRO, RDTRO, TROGRD,       &
     &        TROHES, TRODIP, CUT
      REAL*8 THRESH
      INTEGER IPRINT
      COMMON /CBITRO/ THRESH, IPRINT, COMPAR, SKIP, NOROT1, HESTRO,     &
     &                GDTRO, RDTRO, TROGRD, TROHES, TRODIP, CUT
