C.....requires MXOPEN frpm dcbdhf.h
      INTEGER MAXATOM
      PARAMETER (MAXATOM = 15)
      CHARACTER*6 ATOMFIL(MAXATOM)
      CHARACTER*72 VECATOM(MXOPEN,MAXATOM)
      REAL*8 OCCATOM(MXOPEN,MAXATOM)
      INTEGER NVECATOM(MXATOM)
      COMMON/CBCATOM/ATOMFIL,VECATOM
      COMMON/CBRATOM/OCCATOM
      COMMON/CBIATOM/NVECATOM

