!
! Modified from dcbkrmc.h by sya, 2007.01.25, ulp
! The prefix "KRMC" was changed to "COSC".
! Not all the data are refered by COSCI routine.
! Parametric data NMCFLAG was changed to S_NMCFLAG.
!
!*** COSCI calculations ***
      INTEGER S_NMCFLAG
      PARAMETER (S_NMCFLAG = 20)

      LOGICAL S_MCFLAG(S_NMCFLAG), COSC_SKIPEE, COSC_SKIPEP
      LOGICAL COSC_NOCI, COSC_UCIBOS, COSC_MKCNST
      CHARACTER*8 COSC_CIPROGRAM
      CHARACTER*72 COSC_FRZSTR(2)
      COMMON /DCLCOSC/ MCFLAG, COSC_SKIPEE, COSC_SKIPEP, COSC_NOCI,     &
     &                 COSC_UCIBOS, COSC_MKCNST

      INTEGER NCOSCISH(2), NCOSCASH(2), NCOSCSSH(2),                    &
     &        NCOSCGSH(2, MXGAS), NCOSCGSP(2, MXGAS), NCOSCESH(2),      &
     &        NCOSCPSH(2), NCOSCFRO(2), NCOSCAELEC, NCOSCGAS,           &
     &        NCOSC_MK2REF, NCOSC_MK2DEL, NCOSC_MINMK2, NCOSC_MAXMK2
      COMMON /DCOCOSC/ NCOSCISH, NCOSCASH, NCOSCSSH, NCOSCGSH, NCOSCGSP,&
     &                 NCOSCESH, NCOSCPSH, NCOSCFRO, NCOSCAELEC,        &
     &                 NCOSCGAS, NCOSC_MK2REF, NCOSC_MK2DEL,            &
     &                 NCOSC_MINMK2, NCOSC_MAXMK2
  
      INTEGER ICOSC_ITRINT(2), ICOSC_INTDEF, ICOSC_INTFLG, ICOSC_INTBUF,&
     &        MCOSC_MXMICRO, MCOSC_MXMACRO, MCOSC_MAXBCK, ICOSC_ISTATE, &
     &        ICOSC_SYMMETRY, IPRCOSC
      COMMON /DCICOSC/ ICOSC_ITRINT, ICOSC_INTDEF, ICOSC_INTFLG,        &
     &                 ICOSC_INTBUF, MCOSC_MXMICRO, MCOSC_MXMACRO,      &
     &                 MCOSC_MAXBCK, ICOSC_ISTATE, ICOSC_SYMMETRY,      &
     &                 IPRCOSC

      REAL*8 DCOSC_CNVINT(2), DCOSC_THRGRD, DCOSC_THRPCI
      COMMON /DCRCOSC/ DCOSC_CNVINT, DCOSC_THRGRD, DCOSC_THRPCI

      COMMON /DCCCOSC/ COSC_CIPROGRAM, COSC_FRZSTR
