*** Atomic Huckel start ***
      INTEGER MAXHOC
      PARAMETER (MAXHOC=15)
      CHARACTER*6 HOCFIL(MAXHOC)
      CHARACTER*72 VECHOC(MAXHOC)
      COMMON/DCCHOC/HOCFIL, VECHOC
      COMMON/DCRHOC/HUCPAR
