!*** Vector projection ***
      INTEGER MAXREF
      PARAMETER (MAXREF = 40)

      LOGICAL LWGPOP,OWNBAS,PRJADJ,POLREF,POLNRM,MAYER,PATOMS
      CHARACTER*6 REFFIL(MAXREF)
      CHARACTER*72 VECREF(2, MAXREF), VECPRJ(2)
      COMMON /CBCPRJ/ REFFIL, VECREF, VECPRJ

      INTEGER NREFS, IPRPRJ, NPROJNUC(MAXREF),IREFADJ(2)
      COMMON /CBIPRJ/ NREFS, IPRPRJ, NPROJNUC, IREFADJ

      REAL*8 PROTHR
      COMMON /CBRPRJ/ PROTHR
      COMMON /CBLPRJ/LWGPOP,OWNBAS,PRJADJ,POLREF,POLNRM,MAYER,PATOMS

