      LOGICAL DOREPS(0:7), DOCOOR(3, MXCENT), DCORD(MXCENT, 3, 2),      &
     &        DCORGD(0:MXCENT, 3, 2), DOPERT(0:3*MXCENT, 2)
      INTEGER NDCORD(2)
      COMMON /DORPS/ DOREPS, DOCOOR, NDCORD, DCORD, DCORGD, DOPERT
