      LOGICAL FTRONV, GTRONV, HTRONV, RTRONV, FTWOXP, SORTXP, PTRTXP,   &
     &        NPVTXP, FABRHS, FTRCTL
      INTEGER NASTXP, IPTRAB
      COMMON /EXEINF/ FTRONV, GTRONV, HTRONV, RTRONV, NASTXP, FTWOXP,   &
     &                SORTXP, PTRTXP, NPVTXP, FABRHS, FTRCTL, IPTRAB
