      REAL*8 PRIEXP_FIT(MXPRIM_FIT), PRICCF_FIT(MXPRIM_FIT, MXCONT),    &
     &       PRICRX_FIT(MXPRIM_FIT), PRICRY_FIT(MXPRIM_FIT),            &
     &       PRICRZ_FIT(MXPRIM_FIT)
      INTEGER NPSHEL_FIT, NPLSH_FIT, NPSSH_FIT
      COMMON /FITPRIMIT/ PRIEXP_FIT, PRICCF_FIT, PRICRX_FIT, PRICRY_FIT,&
     &                   PRICRZ_FIT, NPSHEL_FIT, NPLSH_FIT, NPSSH_FIT
