      INTEGER LUMC, LUGDR, LUGDI, LUGDT, LURDR, LURDI, LURDT, LUY,      &
     &        LUSFDA, LUNR1, LUNR3, LUNR5, LUWLK, LUKAP, LUXYDA, LUFJ1, &
     &        LUINTJ, LUTGD, LUTRD, LUZGD, LUZRD, LUTRJ, LUTLM, LUDFCK, &
     &        LRGDR, LRGDI, LRGDT, LRRDR, LRRDI, LRRDT, LRSFDA, LRKAP,  &
     &        LRXYDA, LRTGD, LRTRD, LRTLM, LRDFCK, NBGDR, NBGDI, NBGDT, &
     &        NBRDR, NBRDI, NBRDT, NBSFDA, NBKAP, NBXYDA, NBTGD, NBTRD, &
     &        NBTLM, NBDFCK, LUFDC, LFDCRC
      COMMON /NUCTAP/ LUMC, LUGDR, LUGDI, LUGDT, LURDR, LURDI, LURDT,   &
     &                LUY, LUSFDA, LUNR1, LUNR3, LUNR5, LUWLK, LUKAP,   &
     &                LUXYDA, LUFJ1, LUINTJ, LUTGD, LUTRD, LUZGD, LUZRD,&
     &                LUTRJ, LUTLM, LUDFCK, LRGDR, LRGDI, LRGDT, LRRDR, &
     &                LRRDI, LRRDT, LRSFDA, LRKAP, LRXYDA, LRTGD, LRTRD,&
     &                LRTLM, LRDFCK, NBGDR, NBGDI, NBGDT, NBRDR, NBRDI, &
     &                NBRDT, NBSFDA, NBKAP, NBXYDA, NBTGD, NBTRD, NBTLM,&
     &                NBDFCK, LUFDC, LFDCRC

      CHARACTER*10 ABAMC, ABAGDR, ABAGDI, ABAGDT, ABARDR, ABARDI,       &
     &             ABARDT, ABAY, ABASF, ABAKAP, ABAXY, ABATGD, ABATRD,  &
     &             ABAZGD, ABAZRD, ABATRJ, ABAWLK, ABAIRC, ABATLM,      &
     &             ABADFK
      COMMON /NUCFIL/ ABAMC, ABAGDR, ABAGDI, ABAGDT, ABARDR, ABARDI,    &
     &                ABARDT, ABAY, ABASF, ABAKAP, ABAXY, ABATGD,       &
     &                ABATRD, ABAZGD, ABAZRD, ABATRJ, ABAWLK, ABAIRC,   &
     &                ABATLM, ABADFK
