      LOGICAL TKTIME
      REAL*8 TR000, THERI, TODCVE, TEXCOE, TC10IN, TC1EIN, TC2HIN,      &
     &       TC2EIN, TSYM2S, TSYMOU, TDSOUT, TSPOSY, TDRSYM, TINTEX,    &
     &       TPATH1, TPATH2, TFCKOU, T2INT, THERIX(0:4*MXQN-2),         &
     &       TR000X(0:4*MXQN-2)
      INTEGER LWTOT, MWTOT, MWFCAB, MWFCCD, MWPSO, MWSOIN, MWAOIN,      &
     &        MWHRIN, MWHRND, MWHCIN, MWRJ00, MWHRSQ, MWSCR1, MWC1DR,   &
     &        MWC2DR, MWC2HI, MWC2EI, MWINTE, MWPPRI, MWDRSY, N2WRIT,   &
     &        MXHERMEM(0:3)
      COMMON /TWOSTA/ TR000, THERI, TODCVE, TEXCOE, TC10IN, TC1EIN,     &
     &                TC2HIN, TC2EIN, TSYM2S, TSYMOU, TDSOUT, TSPOSY,   &
     &                TDRSYM, TINTEX, TPATH1, TPATH2, TFCKOU, T2INT,    &
     &                THERIX, TR000X, TKTIME, LWTOT, MWTOT, MWFCAB,     &
     &                MWFCCD, MWPSO, MWSOIN, MWAOIN, MWHRIN, MWHRND,    &
     &                MWHCIN, MWRJ00, MWHRSQ, MWSCR1, MWC1DR, MWC2DR,   &
     &                MWC2HI, MWC2EI, MWINTE, MWPPRI, MWDRSY, N2WRIT,   &
     &                MXHERMEM
