#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Spin-rotation constants (kHz) for',
      to_string   = 'E N D   of   D I R A C  output',
      rel_tolerance   = 1.0e-4)

test.run(['spinrot.inp'], ['H2_cc-pVDZ-sym.mol', 'HF_cc-pVDZ-sym.mol', 'SF6_3-21G-sym.mol'], f, args='--mw=100 --aw=128')

sys.exit(test.return_code)
