#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Natural orbital occupation numbers, symmetry  1',
      num_lines   = 6,
      rel_tolerance   = 1.0e-6)

test.run(['hf.inp' ], ['cinfv.mol'], f, args='--mw=80 --aw=120')
test.run(['hf.inp' ], ['c2v.mol'], f, args='--mw=80 --aw=120' )
test.run(['f2.inp' ], ['dinfh.mol'], f, args='--mw=80 --aw=120')

sys.exit(test.return_code)
