#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Final CCSD energy',
      num_lines   = 7,
      abs_tolerance   = 1.0e-10)
f.add(from_string = 'Electronic energy',
      num_lines   = 8,
      rel_tolerance   = 1.0e-9)
f.add(from_string = 'Eigenvalues',
      num_lines   = 32,
      rel_tolerance   = 1.0e-5)

test.run(['exat_cc_rbh.inp'], ['RbH_nosym.mol'], f)
test.run(['exat_cc_srh.inp'], ['SrH_nosym.mol'], f)

sys.exit(test.return_code)
