#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string    = ' Electronic energy',
      rel_tolerance = 1.0e-10)
f.add(string    = ' Core energy',
      rel_tolerance = 1.0e-8)
# stefan: do NOT test orbital energies - this does not really make sense for open-shells...
#f.add(from_re   = 'Orbital Representation',
#      to_re     = 'Number of determinants',
#      rel_tolerance = 1.0e-7)
f.add(from_re   = 'Energy eigenvalues in atomic units',
      to_re     = 'Total average',
      rel_tolerance = 1.0e-7)

test.run(['ci.inp', 'bss_rkb_sfB.ci.inp', 'bss_rkb_sfE.ci.inp', 'bss_sfB.ci.inp'], ['F.mol'], f)

sys.exit(test.return_code)
