!
!     common block CLUNITR
!
!     assigning logical units
!     logical units are: see luciarel/io_r.F for information
!
      integer   LU2,LU5,LU9,LU19,LU40,LU69,LU70,LU71,
     &          LUSGI1,LUSGI2,LUSGI3,LUSGI4
      COMMON/CLUNITR/LUIN,LUOUT,LUCIVI,LU1INT,LU1SO,LU2INT,
     &              LUPRP,LUDIA,LUC,LUHC,LUSC1,LUSC2,LUSC3,
     &              LUSC34,LUSC35,LUSC36,LUSC37,LUSC38,LUSC39,
     &              LUSC40,LUSC41,LUSC61,LUSC62,
     &              LUCIVO,LUORB,LUMOIN,LUMOUTR,LUMOUTI,
     &              LU2,LU5,LU9,LU19,LU40,LU69,LU70,LU71,
     &              LUSGI1,LUSGI2,LUSGI3,LUSGI4,
     &              LUSC92,LUSC93,LUSC94,LUSC95,LUSC96,
     &              LUSC97,LUSC98,LUSC99,LUPROP_MAT
