      
      INTEGER KSTSM,KZSPGP


      COMMON/STRBASR/KSTINF,KOCSTR(MXPSTT),KNSTSO(MXPSTT),              &
     &              KISTSO(MXPSTT),KSTSTM(MXPSTT,2),KZ(MXPSTT),         &
     &              KSTREO(MXPSTT),KSTSM(MXPSTT),                       &
     &              KNSTSGP(MXPNGAS),KISTSGP(MXPNGAS),                  &
     &              KZSPGP(MXPSTT),KIOCLS,KSPGPAN,KSPGPCR,              &
     &              KNSTSGP2(MXPSTT),KISTSGP2(MXPSTT),                  &
     &              KOCSTR2(MXPSTT),KSTREO2(MXPSTT),                    &
     &              KSTSTM2(MXPSTT,2),KNSTSO2(MXPSTT),KISTSO2(MXPSTT)
