#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '@            isotropic shielding',
      num_lines   = 7,
      rel_tolerance   = 0.002)

# c1
test.run(['scf.inp'], ['co2_c1.mol'], args='--outcmo')

test.run(['lao_shield_lr_rearranged.inp'], ['co2_c1.mol'], f, args='--incmo')
test.run(['lao_shield_lr_rearranged_septep.inp'], ['co2_c1.mol'], f, args='--incmo')
test.run(['lao_shield_rearranged_sc.inp'], ['co2_c1.mol'], f, args='--incmo')
test.run(['lao_shield_rearranged_sc_septep.inp'], ['co2_c1.mol'], f, args='--incmo')
os.unlink('DFCOEF')

# d2h

sys.exit(test.return_code)
