#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Number of determinants/combinations',
      rel_tolerance = 1.0e-5)
f.add(string = ' Final energy',
      rel_tolerance = 1.0e-5)

test.run(['HBr.inp'], ['HBr.mol'], f, args='--mw=60',
                 accepted_errors=['FATAL ERROR for LUCITA runs: memory offset (dynamic memory - static memory) is too big for i*4',
                                  'LUCITA WORK(MXPWRD) memory off-set too big for INTEGER*4'])

sys.exit(test.return_code)
