#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Energies       Transition moments',
      num_lines    = 13,
      abs_tolerance   = 1.0e-9)
#      mask        = [1, 2, 3])

test.run(['fano_real.inp'], ['ne_d2h.mol'],
                 f, args='--mw=64 --aw=130', accepted_errors=['RELADC not parallelized', 'stieltjes not supported in this version'])

sys.exit(test.return_code)
