#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'scalar              x-component         y-component         z-component',
      num_lines   = 3,
      rel_tolerance   = 1.0e-5)

test.run(['nuc_part.inp', 'el_part-coarse.inp'], ['ne.mol'], f)
test.run(['nuc_part.inp'], ['CH4.mol'], f)

f = Filter()
f.add(from_string = 'r_x           r_y           r_z            scalar',
      num_lines   = 5,
      rel_tolerance   = 1.0e-5)

test.run(['el_part-levy-CH4.inp', 'el_part-points.inp'], ['CH4.mol'], f)

sys.exit(test.return_code)
