*** Modified virtual orbitals ***
      CHARACTER VECMVO*72
      LOGICAL IONMVO,ADDREP
      DOUBLE PRECISION MVOWEIGHT
      COMMON/CBLMVO/IONMVO,ADDREP
      COMMON/CBIMVO/IPRMVO,INTMVO,IF2MVO
      COMMON/CBCMVO/VECMVO(2)
      COMMON/CBDMVO/MVOWEIGHT

