#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

options = cli()

f1 = [
    get_filter(string='Electronic energy',
               rel_tolerance=1.0e-7),
]

ierr = 0
for inp, mol in [('minimum.inp', 'ethane_1.mol'),
                 ('saddle.inp', 'ethane_1.mol'),
                 ('constrained.inp', 'ethane_2.mol')]:
    ierr += run(options,
                configure,
                input_files=[inp, mol],
                filters={'out': f1})

f2 = [
    get_filter(from_string='                      PRNRED: Redundant internal coordinates',
               num_lines=37,
               ignore_sign=True,
               rel_tolerance=1.0e-4),
]

for inp, mol in [('findre.inp', 'ethane_2.mol')]:
    ierr += run(options,
                configure,
                input_files=[inp, mol],
                filters={'out': f2})

sys.exit(ierr)
