#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string    = 'Electronic energy',
      rel_tolerance = 1.0e-7)

test.run(['ldaerf.inp', 'ldaerf_jt.inp'], ['he.mol', 'ne.mol'], f)

sys.exit(test.return_code)
