#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Electronic energy',
      rel_tolerance = 1.0e-7)
f.add(string = ' Nonrel. sym.:',
      rel_tolerance = 1.0e-4)

test.run(['pbe0_alda+.inp', 'pbe0_alda-.inp', 'pbe0_alda.inp', 'pbe0_xalda+.inp', 'pbe0_xalda-.inp', 'pbe0_xalda.inp'], ['zn.mol'], f)

sys.exit(test.return_code)
