#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string    = 'Electronic energy',
      rel_tolerance = 1.0e-7)
f.add(from_string = ' Energy eigenvalues in atomic units',
      to_re       = ' Relative real eigenvalues in other units;',
      rel_tolerance   = 1.0e-4)

test.run(['m05.inp', 'm06-l.inp', 'm06.inp'], ['hf.mol'], f)

sys.exit(test.return_code)
