#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '  Magnetizabilities                     au                       SI                      cgs',
      num_lines   = 9,
      rel_tolerance   = 0.0002)


test.run(['dc_pbe.inp'], ['hf.xyz'], args='--outcmo')
test.run(['dc_pbe_magn_sc_g0.inp'], ['hf.xyz'], f, args='--incmo')

os.unlink('DFCOEF')

sys.exit(test.return_code)
