#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Level   Rel eigenvalue     Abs eigenvalue',
      to_string   = ' =====================',
      rel_tolerance   = 1.0e-6)

test.run(['ci.1.inp'],                   ['O.mol'], f)
test.run(['ci.2.inp'],                   ['O.mol'], f, args='--outcmo')
test.run(['ci.3.inp'],                   ['O.mol'], f, args='--incmo ')
test.run(['ci.4.inp'],                   ['O.mol'], f)
test.run(['O.bss_sfB.scf_ci.inp'],       ['O.mol'], f, args='--outcmo')
test.run(['O.bss+mfsso.postscf.ci.inp'], ['O.mol'], f, args='--incmo ')
test.run(['O.bss+mfsso.scf_ci.inp'],     ['O.mol'], f)
test.run(['O.bss.scf_ci.inp'],           ['O.mol'], f)

os.unlink('DFCOEF')

sys.exit(test.return_code)
