#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'd/dg Alpha',
      num_lines   = 10,
      rel_tolerance   = 1.0e-6)
f.add(from_string = 'Gamma =',
      num_lines   = 28,
      rel_tolerance   = 1.0e-6)
f.add(from_string = 'Polarizability (au)',
      to_string   = ' total',
      rel_tolerance   = 1.0e-6)

test.run(['cars_ll.inp'], ['h2o2.mol'], f, args='--put=DALTON.HES')

sys.exit(test.return_code)
