#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Frequency (real)     Real part              Imaginary part         Convergence',
      num_lines   = 16,
      rel_tolerance   = 5.0e-5)

test.run(['cpp.inp'], ['LiH.mol'], f)

sys.exit(test.return_code)
