if(CMAKE_C_COMPILER_ID MATCHES GNU)
    if (${CMAKE_SYSTEM_NAME} STREQUAL "AIX" AND CMAKE_Fortran_COMPILER_ID MATCHES XL AND ENABLE_64BIT_INTEGERS)
        message(STATUS "Added gcc -maix64 flag due to IBM AIX XL Fortran and integer*8")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -maix64 ")
    endif()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g")
    set(CMAKE_C_FLAGS_RELEASE "-O2 -Wno-unused")
    set(CMAKE_C_FLAGS_DEBUG "-O0")
endif()
