if(CMAKE_CXX_COMPILER_ID MATCHES XL)
   if (ENABLE_64BIT_INTEGERS)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -q64")
   else()
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
   endif()
   set(CMAKE_CXX_FLAGS_RELEASE "-O3")
   set(CMAKE_CXX_FLAGS_DEBUG "-O0")
endif()
