if(CMAKE_C_COMPILER_ID MATCHES XL)
    if (ENABLE_64BIT_INTEGERS) 
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -q64")
#   else()
#       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ")
    endif()
    set(CMAKE_C_FLAGS_RELEASE "-O3")
    set(CMAKE_C_FLAGS_DEBUG "-O0")
endif()
