#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

os.environ['OMPI_MCA_btl'] = '^openib'

f = Filter()
f.add(string = 'Total energy                             :',
      rel_tolerance = 1.0e-5)
f.add(from_string = '                                   Eigenvalues',
      to_re       = 'Mulliken population analysis',
      rel_tolerance   = 1.0e-7)

test.run(['NiO6_d8_ECP10SF_4PC.inp'], ['NiO6_d8_ECP10SF_4PC.mol'], f, args='--put DFPCMO')

sys.exit(test.return_code)
