      INTEGER GF_UNIT
      PARAMETER (GF_UNIT = 91)
      CHARACTER*(*) GF_NAME
      PARAMETER (GF_NAME = 'gf-matrix')

      INTEGER LF_UNIT
      PARAMETER (LF_UNIT = 92)
      CHARACTER*(10) LF_NAME

      INTEGER BLOCKSIZE
      PARAMETER (BLOCKSIZE = 8192)

      INTEGER NGBFSZ
C aspg, original code from walter
C     PARAMETER (NGBFSZ = 2047)
C aspg, enlarged parameter
C     PARAMETER (NGBFSZ = 8191)
      PARAMETER (NGBFSZ = ((BLOCKSIZE/4)-1))

      INTEGER MAX_MPI_SIZE
C aspg, original code from walter
      PARAMETER (MAX_MPI_SIZE = 32)
C aspg, enlarged parameter
C     PARAMETER (MAX_MPI_SIZE = 128)

      INTEGER GF_RECLEN, GF_MAXREC
#if defined (INT_STAR8)
      PARAMETER (GF_RECLEN = 8 * BLOCKSIZE)
#else
      PARAMETER (GF_RECLEN = 4 * BLOCKSIZE)
#endif
C aspg, original code from walter
C     PARAMETER (GF_MAXREC = 30000)
C aspg, enlarged parameter
      PARAMETER (GF_MAXREC = 64 * BLOCKSIZE)

      INTEGER N_BUFFER
      PARAMETER (N_BUFFER = 1024)

      INTEGER GF_BREC(N_BUFFER, 0:MAX_MPI_SIZE-1, 0:MAX_MPI_SIZE-1)
      INTEGER GF_NREC(0:MAX_MPI_SIZE-1, 0:MAX_MPI_SIZE-1)
      INTEGER LF_OFFSET(0:MAX_MPI_SIZE-1)
      INTEGER GF_HANDLE, LF_HANDLE
      INTEGER WRITE_REQUEST

      CHARACTER GF_RECBUF(GF_RECLEN)

      COMMON /GF_STATE/  GF_BREC, GF_NREC, LF_OFFSET,
     +   GF_HANDLE, LF_HANDLE, WRITE_REQUEST
      COMMON /GF_BUFFER/ GF_RECBUF
      COMMON /LF_NAME/ LF_NAME
