C
C
C     Include block for parallel timing routine XTIME
C
C
      INTEGER MXTIMF,TCLEAR,TSTART,TSTOP,TPRNTI,TPRNTA,TINIT
      PARAMETER (MXTIMF=100)
      PARAMETER (TCLEAR=0,TSTART=1,TSTOP=2,TPRNTI=3,
     &           TPRNTA=4,TINIT=-1)
C
      REAL*8 CPUTF,CPUTFT
      CHARACTER*30 CPUTT,TIMERF_NAME
      PARAMETER (TIMERF_NAME='.... Empty timer slot ........')
C
      COMMON/TFIELDR/ CPUTF(MXTIMF),CPUTFT(MXTIMF)
      COMMON/TFIELDC/ CPUTT(MXTIMF)
      SAVE LAST_MPE_ACTION, LAST_MPE_STATE
