set(CTEST_NIGHTLY_START_TIME "00:00:00 UTC")
set(CTEST_DROP_METHOD        "http")
set(CTEST_DROP_SITE          "testboard.org")
set(CTEST_DROP_SITE_CDASH    TRUE)

set(CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS 200)
set(UPDATE_TYPE git)

if(DEFINED ENV{CTEST_PROJECT_NAME})
    set(CTEST_PROJECT_NAME  "$ENV{CTEST_PROJECT_NAME}")
    set(CTEST_DROP_LOCATION "/cdash/submit.php?project=$ENV{CTEST_PROJECT_NAME}")
else()
    set(CTEST_PROJECT_NAME  "DIRAC")
    set(CTEST_DROP_LOCATION "/cdash/submit.php?project=DIRAC")
endif()