#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '   * state  1(0g  )         * state',
      num_lines    = 7,
      rel_tolerance = 1.0e-5,
      ignore_sign = True)
f.add(string = '1        0g',
      rel_tolerance = 1.0e-5,
      ignore_sign = True)
f.add(string = '1        4u',
      rel_tolerance = 1.0e-5,
      ignore_sign = True)

test.run(['h2.inp'], ['H2.mol'], f)

sys.exit(test.return_code)
