#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_re     = ' Energy eigenvalues in atomic units',
      to_string   = ' =====================',
      rel_tolerance = 1.0e-5)

test.run(['bss_blockd.ci.inp'], ['F.mol'], f)

f = Filter()
f.add(from_string = 'Number of reference determinants',
      num_lines   = 2,
      rel_tolerance = 1.0e-5)
f.add(from_re     = 'CI Total Energy',
      to_re       = 'Relative to reference',
      rel_tolerance = 1.0e-5)
f.add(from_re     = '.*CI-SD Energy',
      to_re       = '.*CI-SD\+Q energy',
      rel_tolerance = 1.0e-5)

test.run(['F.bss_blockd.cisd.inp'], ['F.1.mol'], f)

sys.exit(test.return_code)
