#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Energy eigenvalues in atomic units',
      num_lines   = 9,
      rel_tolerance = 1.0e-5)

inp_files = []
inp_files.append('ci.inp')
inp_files.append('bss.ci.inp')
inp_files.append('bss_sfBso1.ci.inp')
inp_files.append('bss_sfEso1.ci.inp')
inp_files.append('bss_rkb.ci.inp')
inp_files.append('bss+mfsso.ci.inp')
inp_files.append('bss_sfBso1+mfsso.ci.inp')
inp_files.append('bss_sfEso1+mfsso.ci.inp')
inp_files.append('bss_rkb+mfsso.ci.inp')
inp_files.append('dkh2.ci.inp')
inp_files.append('dkh2+mfsso.ci.inp')
inp_files.append('dkh2sfBso1+mfsso.ci.inp')
inp_files.append('dkh2sfEso1+mfsso.ci.inp')
inp_files.append('dkh2sfBso1.ci.inp')
inp_files.append('dkh2sfEso1.ci.inp')

test.run(inp_files, ['F.mol'], f)

inp_files = []
inp_files.append('ci.inp')
inp_files.append('bss.ci.inp')
inp_files.append('dkh2.ci.inp')
inp_files.append('bss_rkb.ci.inp')
inp_files.append('dkh2+mfsso_Flike.ci.inp')
inp_files.append('dkh2sfBso1.ci.inp')
inp_files.append('dkh2sfBso1+mfsso.ci_Flike.inp')
inp_files.append('bss+mfsso.ci_Flike.inp')

test.run(inp_files, ['Z86_Flike.mol'], f)

sys.exit(test.return_code)
