#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Total energy',
      rel_tolerance = 1.0e-7)

test.run(['hf.inp'], ['ethanol.xyz'], f)
test.run(['emb.inp'], ['methanol.xyz'], f)
test.run(['heh+.inp'], ['heh.xyz'], f)

sys.exit(test.return_code)
