#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '@            isotropic shielding',
      num_lines   = 7,
      rel_tolerance   = 0.002)


test.run(['sdft_lda_dc_shielding.inp'],
                 ['hf_c1.mol', 'hf_c2v.mol', 'hf_c2.mol'], f)

test.run(['sdft_b3lyp_dc_shielding.inp'],
                 ['hf_c1.mol', 'hf_c2v.mol', 'hf_c2.mol'], f)

sys.exit(test.return_code)
