#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string    = '@ gamma',
      rel_tolerance = 1.0e-6)
f.add(string    = '@ averaged gamma',
      rel_tolerance = 1.0e-6)

test.run(['levy.inp'], ['mol.mol'], f)

sys.exit(test.return_code)
