module xcfun_autogen
!  this file is generated by generate_interfaces.py - do not edit
   implicit none
   integer, parameter :: XC_NR_PARAMS = 40
   integer, parameter :: XC_SLATERX = 1
   integer, parameter :: XC_VWN5C = 2
   integer, parameter :: XC_BECKEX = 3
   integer, parameter :: XC_BECKECORRX = 4
   integer, parameter :: XC_BECKESRX = 5
   integer, parameter :: XC_OPTX = 6
   integer, parameter :: XC_LYPC = 7
   integer, parameter :: XC_PBEX = 8
   integer, parameter :: XC_REVPBEX = 9
   integer, parameter :: XC_RPBEX = 10
   integer, parameter :: XC_PBEC = 11
   integer, parameter :: XC_SPBEC = 12
   integer, parameter :: XC_VWN_PBEC = 13
   integer, parameter :: XC_LDAERFX = 14
   integer, parameter :: XC_LDAERFC = 15
   integer, parameter :: XC_LDAERFC_JT = 16
   integer, parameter :: XC_RANGESEP_MU = 17
   integer, parameter :: XC_KTX = 18
   integer, parameter :: XC_TFK = 19
   integer, parameter :: XC_PW86X = 20
   integer, parameter :: XC_P86C = 21
   integer, parameter :: XC_PW91X = 22
   integer, parameter :: XC_PW91K = 23
   integer, parameter :: XC_PW92C = 24
   integer, parameter :: XC_M05X = 25
   integer, parameter :: XC_M05X2X = 26
   integer, parameter :: XC_M06X = 27
   integer, parameter :: XC_M06X2X = 28
   integer, parameter :: XC_M06LX = 29
   integer, parameter :: XC_M06HFX = 30
   integer, parameter :: XC_BRX = 31
   integer, parameter :: XC_M05X2C = 32
   integer, parameter :: XC_M05C = 33
   integer, parameter :: XC_M06C = 34
   integer, parameter :: XC_M06LC = 35
   integer, parameter :: XC_M06X2C = 36
   integer, parameter :: XC_TPSSC = 37
   integer, parameter :: XC_TPSSX = 38
   integer, parameter :: XC_REVTPSSC = 39
   integer, parameter :: XC_REVTPSSX = 40
end module
