#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'SCF energy :',
      num_lines   = 3,
      rel_tolerance   = 1.0e-9)
f.add(from_string = 'Electronic energy',
      num_lines   = 8,
      rel_tolerance   = 1.0e-9)
f.add(from_string = 'Eigenvalues',
      num_lines   = 32,
      rel_tolerance   = 1.0e-5)

# these are longer tests
#test.run(['cc2_energy.inp'], ['LiH', 'h2o.xyz'], f)
#test.run(['cc2_energy_large_cvalue.inp'], ['LiH', 'h2o.xyz'], f)

test.run(['cc2_energy_small.inp'], ['LiH', 'h2o.xyz'], f)

sys.exit(test.return_code)
