#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '@   Elements of the electric dipole',
      num_lines   = 58,
      rel_tolerance   = 1.0e-4)

test.run(['dc.inp', 'bss.inp', 'bss+mfsso.inp', 'bss_rkb+mfsso.inp'], ['H2O.mol'], f)

sys.exit(test.return_code)
