#!/usr/bin/env python

import os
import sys
import shutil

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

# Testing regular and Fock space coupled cluster
f = Filter()
f.add(from_string = 'TOTAL ENERGY',
      num_lines   = 10,
      rel_tolerance   = 1.0e-8)

f.add(from_string = ' Overview of calculated energies',
      to_string   = '@ Total CCSD-T  energy',
      abs_tolerance   = 1.0e-4)

#test.run(['ccsd_o2.inp'], ['O2_d2h.mol'], f, args='--mw=120 ')
#test.run(['ccsd_aoc_o2.inp'], ['O2_d2h.mol'], f, args='--mw=120 ')
test.run(['ccsd_mcscf_o2.inp'], ['O2_d2h.mol'], f, args='--mw=120 ')

sys.exit(test.return_code)
