#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

f = [
    get_filter(from_string='Overview of calculated energies',
               to_string='--------------------------------------------------------------------------------',
               abs_tolerance=1.0e-09)
]

options = cli()

ierr = 0
for inp in ['MgF.dc_rkb.scf_relcc_Wa-xalpha.1e-6.inp']:
    for mol in ['MgF.sto-2g.Cs_y.mol']:
        ierr += run(options,
                    configure,
                    input_files=[inp, mol],
                    filters={'out': f})

for inp in ['MgOH.dc_rkb.scf_relcc_Wa-xalpha.-1e-6.inp']:
    for mol in ['MgOH.sto-2g.Cs_y.mol']:
        ierr += run(options,
                    configure,
                    input_files=[inp, mol],
                    filters={'out': f})

sys.exit(ierr)

