#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Total :',
      rel_tolerance   = 1.0e-5)

test.run(['Rhonuc.inp'], ['CO.mol'], f)

sys.exit(test.return_code)
