#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string      = 'Electronic energy',
      rel_tolerance   = 1.0e-7)
f.add(from_string = '* Dipole moment:',
      num_lines   = 12,
      rel_tolerance   = 1.0e-6)

mol = []
mol.append('Turbomole-DZP.mol')
mol.append('Turbomole-TZVPP.mol')
mol.append('aug-cc-pVDZ.mol')
mol.append('d-a-Turbomole-DZP.mol')
mol.append('d-aug-cc-pVDZ.mol')
mol.append('d-aug-dyall.v2z.mol')
mol.append('dyall.v2z.mol')
mol.append('s-a-Turbomole-DZP.mol')
mol.append('s-a-Turbomole-TZVPP.mol')
mol.append('t-aug-cc-pVDZ.mol')

test.run(['hf.inp'], mol, f)

sys.exit(test.return_code)
