.\"This file was created by jth Jan 11 1999"
.TH labread 1
.SH NAME
.B labread
- Check for MOLECULE records on files
.SH SYNOPSIS
labread file1 file2 ...

.SH DESCRIPTION
.B labread
checks for MOLECULE records in on the files
.B file1 file2 ...
.SH FILES
labread
.SH BUGS
None (of course)
.SH AUTHORS
Written by Hans Jorgen Aa. Jensen, Nov. 1983
.PP
Rewritten to work on IBM and Linux by J. Thyssen 
(joern@thyssen.nu), Jan. 1999
