#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '           Electric-field-gradient-induced',
      num_lines   = 12,
      rel_tolerance   = 1.0e-6)

test.run(['lda.inp', 'blyp.inp', 'blyp_shifted.inp'], ['mol.mol'], f)

sys.exit(test.return_code)
