#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '           Electric-field-gradient-induced',
      num_lines   = 12,
      rel_tolerance   = 1.0e-6)

test.run(['nr_hf.inp'], ['h2o2.mol'], f)
test.run(['nr_hf.inp', 'nr_hf_shifted.inp', 'dc_hf_skipep.inp', 'dc_hf_skipep_cval=3000.inp', 'dc_hf.inp', 'dc_hf_shifted.inp'], ['fh.mol'], f)

sys.exit(test.return_code)
