#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string    = '    < state | Z1-MQM [alpha X EFG] | state > ',
      num_lines    = 5,
      rel_tolerance = 1.0e-4)
f.add(from_string    = '    < state | Z2-MQM [alpha X EFG] | state > ',
      num_lines    = 5,
      rel_tolerance = 1.0e-4)

test.run(['BeH_nmqm_key.inp'], ['BeH.mol'], f)

f = Filter()
f.add(from_string    = '     < state |      Z1-MQM      | state > ',
      num_lines    = 5,
      rel_tolerance = 1.0e-4)
f.add(from_string    = '     < state |      Z2-MQM      | state > ',
      num_lines    = 5,
      rel_tolerance = 1.0e-4)

test.run(['BeH_nmqm_def.inp'], ['BeH.mol'], f)

sys.exit(test.return_code)
