#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Overview of calculated energies',
      num_lines   = 4,
      rel_tolerance   = 1.0e-8)

test.run(['MP2.inp'], ['H2O.mol'], f)

sys.exit(test.return_code)
