#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'r_x           r_y           r_z            scalar',
      num_lines    = 7,
      rel_tolerance = 1.0e-5)

test.run(['elf.inp'], ['ar.mol'], f)

sys.exit(test.return_code)
