#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

# filter covers wide range of outputs from SYMADD, SYMGRP, DBLGRP and from basis set processing;
# also checks the QM-QM nuclear repulsion energy
f = [
    get_filter(from_string='SYMADD: Detection of molecular symmetry',
               to_string='References for the basis sets',
               rel_tolerance=1.0e-8)
]

options = cli()

ierr = 0
for n in range(1, 19):
    ierr += run(options,
                configure,
                input_files=['test_xyz.inp', 'molecule{0:02}.xyz'.format(n)],
                filters={'out': f})

sys.exit(ierr)
