#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'scalar              x-component',
      num_lines   = 3,
      rel_tolerance   = 1.0e-5)

test.run(['density_1s.inp', 'density_4s.inp', 'density_total.inp'], ['he.mol'], f)
test.run(['density_1s.inp', 'density_4s.inp', 'density_total.inp', 'density_total_orbstring.inp'], ['ne.mol'], f)

f = Filter()
f.add(from_re     = 'r_x           r_y           r_z            scalar',
      num_lines   = 7,
      rel_tolerance   = 1.0e-5)

test.run(['density_n.inp'], ['n.mol'], f)

sys.exit(test.return_code)
