#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'SYMGRP:Point group information',
      to_string='References for the basis sets',
      rel_tolerance   = 1.0e-8)
f.add(from_string = 'TOTAL ENERGY',
      num_lines   = 11,
      rel_tolerance   = 1.0e-9)

mol_files = ['ne_auto.mol', 'ne_c1.mol', 'ne_c2.mol', 'ne_c2h.mol', 'ne_c2v.mol', 'ne_ci.mol', 'ne_cs.mol', 'ne_d2.mol', 'ne_d2h.mol']
inp_files = ['dc.inp', 'dc_sof.inp', 'dc_urkbal.inp', 'nr.inp', 'x2c.inp', 'x2c4.inp']

test.run(inp_files, mol_files, f)

sys.exit(test.return_code)
