#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = '@            isotropic shielding',
      num_lines   = 7,
      rel_tolerance   = 0.002)

inp_files = []
inp_files.append('LiH.levyle.shield_lao_go=cm.inp')
inp_files.append('LiH.dc_ukb.shield_lao_go=cm.inp')
inp_files.append('LiH.dc_rkb.shield_lao_go=cm.inp')
inp_files.append('LiH.dc_sf.shield_lao_go=cm.inp')
inp_files.append('LiH.bss.shield_lao_go=cm.inp')
inp_files.append('LiH.bss+mfsso.shield_lao_go=cm.inp')
inp_files.append('LiH.bss_sfB.shield_lao_go=cm.inp')

test.run(inp_files, ['LiH.lsym.dir.mol'], f)

sys.exit(test.return_code)
