#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Energy eigenvalues in atomic units',
      to_re     = ' Relative real eigenvalues in other units;',
      abs_tolerance = 1.0e-4)

test.run(['lda_sigma.inp', 'lda_betasigma.inp', 'blyp_sigma.inp', 'blyp_betasigma.inp'], ['he.mol'], f)

sys.exit(test.return_code)
