#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'diagonalize the one-electron matrix',
      num_lines   = 8,
      rel_tolerance   = 1.0e-6)

test.run(['hf.inp'], ['h2.xyz'], f)

sys.exit(test.return_code)

