C
C     DEFINITION PARAMETERS GOSCIP
C
C     N1:  MAXIMUM NUMBER OF BASISFUNCTIONS (NOT LARGER THAN 32 !)
C     N2:  MAXIMUM NUMBER OF DETERMINANTS
C     N5:  MAXIMUM NUMBER OF (ABELIAN) REPRESENTATIONS
C
      PARAMETER (N1 = 24)
      PARAMETER (N2 = 4000)
      PARAMETER (N3 = N1*N1)
      PARAMETER (N4 = N3*N3)
      PARAMETER (N4A = 10000)
      PARAMETER (N5 = 32)
      PARAMETER (N5A=N5*2, N5B=2*N5*(2*N5+1))
C
C     DEFINITION GENERAL COMMON BLOCKS GOSCIP
C
      COMMON /GORAS/ IMINH1,IMAXH1,IMAXE3,IRAS1,IRAS3,IEL3
!
      COMMON /GODATIN/ NSPACT,NELACT,IREF,IREFE,NREP,IPRNT,IN_FCIDUMP
      COMMON /GOBRINT/ BREIT,REALAR
      COMMON /GODPTAB/ MULTB(2*N5,0:2*N5),IRPAMO(N1)
      COMMON /GOCHR/ REPNA(2*N5)
      COMMON /GODETS/ IDET (N2), NDET, NDETMX
C
      CHARACTER*4 REPNA
      LOGICAL BREIT,REALAR
C  
C     DEFINITION DATA COMMON BLOCKS GOSCIP
C
      COMMON /GOSBAS/ EPS(N1),ECORE
      COMMON /GOSCIN/ONER(N1,N1),ONEI(N1,N1)
      COMMON /GOSRESULT/ D(N2,N5),NDETI(N5)
C
      COMMON/POPANA/THRESH,DEGEN,SELPOP,MAXPOP
