#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_re   = 'molecular gradient',
      num_lines = 6,
      rel_tolerance = 1.0e-6)

test.run(['hf_ll.inp', 'hf_dc.inp', 'hf_dc_cval=5.inp'], ['h2o2.mol'], f)
test.run(['lda_ll.inp', 'b3lyp_ll.inp', 'blyp_ll.inp'], ['h2o2.mol'], f)

sys.exit(test.return_code)
