#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string    = ' EEDM', rel_tolerance = 1.0e-4)
f.add(string    = ' MHYP', rel_tolerance = 1.0e-4)
f.add(string    = ' ENSPS', rel_tolerance = 1.0e-4)

test.run(['BeH.inp'], ['BeH.mol'], f)

sys.exit(test.return_code)
