#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'Expectation values',
      to_string   = '    s0 = T : Expectation value zero by point group symmetry.',
      rel_tolerance = 1.0e-5)
f.add(from_string = 'DIRAC  - INDIRECT NUCLEAR SPIN-SPIN-COUPLINGS',
      to_string   = 'DSO contribution to reduced SSCC K (SI:10**19 m-2 kg s-2 A-2)',
      rel_tolerance = 1.0e-5)
f.add(from_string = 'At1  #  iso',
      num_lines   = 4,
      rel_tolerance   = 1.0e-3)

test.run(['levy-leblond.inp'], ['H2O.mol'], f)

sys.exit(test.return_code)
