#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = '@            isotropic shielding',
      num_lines   = 5,
      rel_tolerance   = 0.0002)

test.run(['rkb.inp'], ['He.mol'], f, args='--outcmo')
test.run(['rkbimp.inp'], ['He.mol'], f, args='--incmo')
test.run(['ukb.inp'], ['He.mol'], f)

os.unlink('DFCOEF')

sys.exit(test.return_code)
