#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'no.    eigenvalue (eV)   mean-res.',
      num_lines    = 4,
      rel_tolerance   = 1.0e-4)

test.run(['real_ne_dip.inp'], ['ne_d2h.mol'], f, accepted_errors=['RELADC not parallelized'])
test.run(['complex_hcn_dip.inp'], ['hcn_cs.mol'], f, accepted_errors=['RELADC not parallelized'])

sys.exit(test.return_code)
