#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '* Electric field gradients',
      num_lines   = 54,
      rel_tolerance   = 1.0e-6)

test.run(['fde_dc_lda_short.inp', 'fde_dc_hf_short.inp', 'fde_ll_hf_short.inp'], ['water.sto6g.mol'], f, args='--mw=80 --nw=80 --aw=90 --put=vemb.grid')
test.run(['fde_dc_lda_short.inp', 'fde_dc_hf_short.inp', 'fde_ll_hf_short.inp'], ['water.sto6g.c2v.mol'], f, args='--mw=80 --nw=80 --aw=90 --put=vemb.grid')

sys.exit(test.return_code)
