#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'TOTAL ENERGY',
      num_lines   = 11,
      rel_tolerance   = 1.0e-9)

test.run(['cosci.Li2.inp'], ['Li2.mol'],  f, args='--mw=120')
test.run(['cosci.H3.inp'], ['H3.mol'],  f, args='--mw=120')

sys.exit(test.return_code)
