#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = '! Dispersion coefficient !',
      num_lines   = 9,
      rel_tolerance   = 5.0e-7)

test.run(['C6.inp'], ['Ne.mol'], f)

sys.exit(test.return_code)
